steps:
  # Install dependencies for VirtuSphere backend
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'VirtuSphere/backend'
    args: ['install']
    id: 'install-virtusphere-backend-deps'

  # Install dependencies for V-Analyzer backend
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'VirtuSphere/V-Analyzer'
    args: ['install']
    id: 'install-v-analyzer-deps'
    waitFor: ['-']

  # Install dependencies for V-DevContainers backend
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'VirtuSphere/V-DevContainers/backend'
    args: ['install']
    id: 'install-v-devcontainers-deps'
    waitFor: ['-']

  # Build V-Analyzer frontend
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'VirtuSphere/V-Analyzer/frontend'
    args: ['install']
    id: 'install-v-analyzer-frontend-deps'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'VirtuSphere/V-Analyzer/frontend'
    args: ['run', 'build']
    id: 'build-v-analyzer-frontend'
    waitFor: ['install-v-analyzer-frontend-deps']
    env:
      - 'CI=false'

  # Build V-DevContainers frontend
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'VirtuSphere/V-DevContainers/frontend'
    args: ['install']
    id: 'install-v-devcontainers-frontend-deps'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'VirtuSphere/V-DevContainers/frontend'
    args: ['run', 'build']
    id: 'build-v-devcontainers-frontend'
    waitFor: ['install-v-devcontainers-frontend-deps']
    env:
      - 'CI=false'

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'VirtuSphere/app.yaml', '--quiet']
    id: 'deploy-to-app-engine'
    waitFor:
      - 'install-virtusphere-backend-deps'
      - 'install-v-analyzer-deps'
      - 'install-v-devcontainers-deps'
      - 'build-v-analyzer-frontend'
      - 'build-v-devcontainers-frontend'

timeout: '1800s'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
